import { Late } from '@getlatedev/node';
import type { Outcome, Platform, Publication } from './types.js';
import { numberFromEnv } from './config.js';

interface AccountConfig {
  twitter?: string;
  linkedin?: string;
}

/**
 * The Late SDK is generated by hey-api: every call resolves to
 * `{ data, error }` rather than the payload directly, and the payload for a
 * post is `{ message, post }`.
 *
 * postToX used to return the whole envelope while postToLinkedIn returned
 * `response.data.post`, so `result.x._id` was always undefined and every X
 * post id was logged as null — leaving those posts permanently unmeasurable.
 * Unwrapping happens in exactly one place now.
 */
interface LateEnvelope<T> {
  data?: T;
  error?: unknown;
}

interface LatePost {
  _id?: string;
  status?: string;
  scheduledFor?: string;
  publishedAt?: string;
}

const PUBLISH_TIMEOUT_MS = numberFromEnv('PUBLISH_TIMEOUT_MS', 30_000);

export class LatePublisher {
  private readonly late: Late;
  private readonly accountIds: AccountConfig;

  constructor(apiKey?: string, accountIds?: AccountConfig) {
    const key = apiKey ?? process.env.LATE_API_KEY;
    if (!key) throw new Error('Late API key is required (set LATE_API_KEY)');

    this.late = new Late({ apiKey: key });
    this.accountIds = accountIds ?? {
      twitter: process.env.LATE_TWITTER_ACCOUNT_ID,
      linkedin: process.env.LATE_LINKEDIN_ACCOUNT_ID,
    };
  }

  accountFor(platform: Platform): string | undefined {
    return this.accountIds[platform];
  }

  private async withTimeout<T>(promise: Promise<T>, operation: string): Promise<T> {
    let timer: NodeJS.Timeout | undefined;

    try {
      return await Promise.race([
        promise,
        new Promise<never>((_, reject) => {
          timer = setTimeout(
            () => reject(new Error(`${operation} timed out after ${PUBLISH_TIMEOUT_MS}ms`)),
            PUBLISH_TIMEOUT_MS,
          );
        }),
      ]);
    } finally {
      // Without this the timer keeps the process alive for the full timeout
      // even after a fast success — which is why runs appeared to hang.
      if (timer) clearTimeout(timer);
    }
  }

  /** Single normalisation point for every Late response. */
  private unwrap<T>(envelope: unknown, operation: string): T {
    const { data, error } = (envelope ?? {}) as LateEnvelope<T>;

    if (error) {
      throw new Error(`${operation} failed: ${JSON.stringify(error)}`);
    }
    if (!data) {
      throw new Error(`${operation} returned no data: ${JSON.stringify(envelope)}`);
    }

    return data;
  }

  /**
   * Publish (or schedule) one post. Returns a `Publication` — the ledger's
   * shape — so the caller never has to know Late's response format.
   */
  async publish(platform: Platform, text: string, scheduledFor?: Date): Promise<Publication> {
    const accountId = this.accountIds[platform];
    if (!accountId) {
      throw new Error(`${platform} account ID not configured`);
    }

    const body: Record<string, unknown> = {
      content: text,
      platforms: [{ platform, accountId }],
    };

    if (scheduledFor) {
      body.scheduledFor = scheduledFor.toISOString();
    } else {
      body.publishNow = true;
    }

    const envelope = await this.withTimeout(
      this.late.posts.createPost({ body }) as Promise<unknown>,
      `${platform} post`,
    );

    const { post } = this.unwrap<{ post?: LatePost }>(envelope, `${platform} post`);
    if (!post?._id) {
      throw new Error(`${platform} post created without an id: ${JSON.stringify(post)}`);
    }

    return {
      platform,
      latePostId: post._id,
      status: scheduledFor ? 'scheduled' : 'published',
      scheduledFor: post.scheduledFor ?? scheduledFor?.toISOString(),
      publishedAt: post.publishedAt ?? (scheduledFor ? undefined : new Date().toISOString()),
    };
  }

  /**
   * Publish to several platforms at once.
   *
   * Uses allSettled, not all: a LinkedIn failure used to reject the whole
   * Promise.all and discard a successful X publish along with its id, so the
   * post existed on the platform but not in any record we kept.
   */
  async publishMany(
    items: { platform: Platform; text: string }[],
    scheduledFor?: Date,
  ): Promise<Publication[]> {
    const results = await Promise.allSettled(
      items.map((item) => this.publish(item.platform, item.text, scheduledFor)),
    );

    return results.map((result, i) =>
      result.status === 'fulfilled'
        ? result.value
        : {
            platform: items[i].platform,
            latePostId: null,
            status: 'failed' as const,
            error: (result.reason as Error).message,
          },
    );
  }

  /**
   * Read engagement back for a published post.
   *
   * The SDK has exposed this the whole time; nothing ever called it, which is
   * why no post's performance has ever fed back into what gets written next.
   */
  async getOutcome(platform: Platform, latePostId: string): Promise<Outcome | undefined> {
    const envelope = await this.withTimeout(
      this.late.analytics.getAnalytics({ query: { postId: latePostId } }) as Promise<unknown>,
      'analytics fetch',
    );

    const data = this.unwrap<{
      analytics?: {
        impressions?: number;
        likes?: number;
        comments?: number;
        shares?: number;
        clicks?: number;
        engagementRate?: number;
      };
    }>(envelope, 'analytics fetch');

    if (!data.analytics) return undefined;

    return {
      platform,
      collectedAt: new Date().toISOString(),
      impressions: data.analytics.impressions,
      likes: data.analytics.likes,
      comments: data.analytics.comments,
      shares: data.analytics.shares,
      clicks: data.analytics.clicks,
      engagementRate: data.analytics.engagementRate,
    };
  }

  async getPostStatus(latePostId: string): Promise<LatePost | undefined> {
    const envelope = await this.withTimeout(
      this.late.posts.getPost({ postId: latePostId }) as Promise<unknown>,
      'post status',
    );

    return this.unwrap<{ post?: LatePost }>(envelope, 'post status').post;
  }

  async deletePost(latePostId: string): Promise<void> {
    await this.withTimeout(
      this.late.posts.deletePost({ postId: latePostId }) as Promise<unknown>,
      'post delete',
    );
  }
}
